steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cra-docker:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'cra-docker=gcr.io/$PROJECT_ID/cra-docker:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', 'cra-docker', '--image=gcr.io/$PROJECT_ID/cra-docker:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cra-docker'
images:
- 'gcr.io/$PROJECT_ID/cra-docker'
tags:
- 'demo'
- 'nodejs'
