steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
<<<<<<< HEAD
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cra-docker-stage:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cra-docker-stage:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/cra-docker-stage', 'cra-docker=gcr.io/$PROJECT_ID/cra-docker-stage:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cra-docker-stage'
images:
- 'gcr.io/$PROJECT_ID/cra-docker-stage'
=======
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cra-docker-master:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cra-docker-master:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/cra-docker-master', 'cra-docker=gcr.io/$PROJECT_ID/cra-docker-master:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cra-docker-master'
images:
- 'gcr.io/$PROJECT_ID/cra-docker-master'
>>>>>>> master
tags:
- 'demo'
- 'nodejs'